
/*
 * ZipInput.java
 * 
 * Versions
 * 		10/21/2017
 * 
 * Revisions
 * 		7.3.a
 */

import java.io.*;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * 
 * This program will read the file that has been generated by the ZipOutput
 * Class and verify the hashcode which was appended at last of the line. If the
 * hashcode matches then it will print the result. Else it throw the user
 * defined exception
 * 
 * 
 * @author Maha Krishnan Krishnan
 * @author Kunal Nayyar
 *
 */
public class ZipInput {
	File file;
	String inputHashCode;
	public ZipInput(File file) {
		this.file = file;
	}
	/**
	 * This is the input method
	 * 
	 */
	public void input() {

		// Importing the file
		try {

			// Reading the file
			FileReader fileReader = new FileReader(file);
			BufferedReader bufferedReader = new BufferedReader(fileReader);

			// Store the content of the file into the text
			String tempText = bufferedReader.readLine();
			String text = "";
			while (tempText != null) {
				text = text + tempText + "\n";
				tempText = bufferedReader.readLine();
			}

			// Spliting the strings to get the hashcode which has been generated from the
			// ZipOutput class
			String split[] = text.split("Hashcode::");

			// Generating the hashcode which has been read from the file
			MessageDigest m = java.security.MessageDigest.getInstance("MD5");
			m.update(split[0].getBytes());

			byte[] bytedigest = m.digest();
			StringBuffer sbwritten = new StringBuffer(bytedigest.length * 2);
			for (byte b : bytedigest)
				sbwritten.append(String.format("%02x", b));

			inputHashCode = sbwritten.toString();

			// Check whether both the hashcode values are correct. Else it will hashcode
			// Exception which was user defined one.
			if (!inputHashCode.equals(split[1].trim())) {
				bufferedReader.close();
				throw new HashCodeException();
			}

			// Print the contents of the file into the console
			System.out.println("Text in the zip file is::");
			System.out.println(split[0]);
			bufferedReader.close();

		} catch (IOException e) {
			System.out.println("IO Exception Occurs");
			e.printStackTrace();
		} catch (HashCodeException hash) { // User defined Exception Class
			System.err.println(hash);
			System.err.println("HashCode Exception");
		} catch (NoSuchAlgorithmException e) {
			System.out.println("NoSuchAlgorithmException");
			e.printStackTrace();
		}
	}
}
